
---
title: "DNA damage-Linear mixed effects model"
author: "Or Ben-Zvi"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
  
##load packages
```{r message=FALSE, warning=FALSE}
library(car) 
library(ggplot2) 
library(lme4)
library(lmerTest)
library(dplyr)
library(MASS) 
library(cowplot)
library(doBy)
```

##read data
```{r}
data_dna<- read.csv(file.choose())
```
```{r}
str(data_dna)
```
#Plot the data
```{r eval=FALSE}
qqplot(data_dna$morph,data_dna$cpd)
plot(data_dna$morph,data_dna$cpd)
qqplot(data_dna$morph,data_dna$pp)
plot(data_dna$morph,data_dna$pp)
```

##Test with mixed effect model
```{r}
model_cpd <- lmer(cpd ~ treatment*morph + (1|colony),
                   data=data_dna, REML=FALSE)
summary(model_cpd)
anova(model_cpd)

model_cpd1 <- lmer(cpd ~ treatment + (1|colony),
                   data=data_dna, REML=FALSE)

model_cpd2 <- lmer(cpd ~ morph + (1|colony),
                   data=data_dna, REML=FALSE)

anova(model_cpd, model_cpd1)
anova(model_cpd, model_cpd2)


model_pp <-  lmer(pp ~ treatment*morph + (1|colony),
                   data=data_dna, REML=FALSE)
summary(model_pp)
anova(model_pp)


model_pp1 <-  lmer(pp ~ treatment + (1|colony),
                   data=data_dna, REML=FALSE)


model_pp2 <-  lmer(pp ~ morph + (1|colony),
                   data=data_dna, REML=FALSE)

anova(model_pp, model_pp1)
anova(model_pp, model_pp2)
```
##Check the LMM assumptions
#Check the normality of model residuals
```{r}
qqnorm(resid(model_cpd))
qqline(resid(model_cpd))

qqnorm(resid(model_pp))
qqline(resid(model_pp))
```
#Check for homogenity of variance
```{r}
plot(model_cpd)
plot(model_pp)
```
##Obtain mean and SD
```{r}
sumfun <- function(x, ...){
  c(mean=mean(x, na.rm=TRUE, ...), sd=sd(x, na.rm=TRUE, ...), l=length(x))
}
mean(data_dna$cpd, na.rm = TRUE)
sd(data_dna$cpd, na.rm = TRUE)
summaryBy(cpd ~ morph * treatment, data=data_dna, FUN=sumfun)
summaryBy(cpd ~ morph, data=data_dna, FUN=sumfun)
summaryBy(cpd ~ treatment, data=data_dna, FUN=sumfun)
mean(data_dna$pp, na.rm = TRUE)
sd(data_dna$pp, na.rm = TRUE)
summaryBy(pp ~morph * treatment, data=data_dna, FUN=sumfun)
summaryBy(pp ~morph, data=data_dna, FUN=sumfun)
summaryBy(pp ~treatment, data=data_dna, FUN=sumfun)

```

##Visualize the data as a box plot
```{r}
cpd_plot <- ggplot(data = data_dna, aes(x=morph, y=cpd)) + 
  geom_boxplot(aes(fill=treatment)) +
  labs(x="Fluorescence morph", y="CPD-DNA concentration(ng mL^-1)") + 
  scale_fill_grey(start = 0.4, end = 0.8, name="Treatment",breaks=c("par", "paruv"), labels=c("PAR","PAR+UV")) + 
  theme_bw() +
  theme(legend.position="right")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
cpd_plot
```

```{r}
pp_plot <- ggplot(data = data_dna, aes(x=morph, y=pp)) + 
  geom_boxplot(aes(fill=treatment)) +
  labs(x="Fluorescence morph", y="6-4PP-DNA concentration(ng mL^-1)") + 
  scale_fill_grey(start = 0.4, end = 0.8, name="Treatment",breaks=c("par", "paruv"), labels=c("PAR","PAR+UV")) + 
  theme_bw() +
  theme(legend.position="none")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
pp_plot
```



