---
title: "Host protein and MAA concentration-Linear mixed effects model"
author: "Or Ben-Zvi"
output:  
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##load packages
```{r message=FALSE, warning=FALSE}
library(car) 
library(ggplot2) 
library(lme4)
library(lmerTest)
library(MASS) 
library(cowplot)
library(dplyr)
library(doBy)
```
##read data
```{r}
data_hpmaa <- read.csv(file.choose())
```
```{r warning=FALSE}
str(data_hpmaa)
data_hpmaa$hpt0 <- as.numeric(as.character(data_hpmaa$hpt0))
data_hpmaa$hpt1 <- as.numeric(as.character(data_hpmaa$hpt1))
data_hpmaa$maat0 <- as.numeric(as.character(data_hpmaa$maat0))
data_hpmaa$maat1 <- as.numeric(as.character(data_hpmaa$maat1))
data_hpmaa$dhp <- as.numeric(as.character(data_hpmaa$dhp))
data_hpmaa$dmaa <- as.numeric(as.character(data_hpmaa$dmaa))
data_hpmaa$php <- as.numeric(as.character(data_hpmaa$php))
data_hpmaa$pmaa <- as.numeric(as.character(data_hpmaa$pmaa))
data_hpmaa$tank <- as.factor(data_hpmaa$tank)
str(data_hpmaa)
```
##Visualize data
```{r}
qqplot(data_hpmaa$morph,data_hpmaa$dhp)
plot(data_hpmaa$morph,data_hpmaa$dhp)
qqplot(data_hpmaa$morph,data_hpmaa$dmaa)
plot(data_hpmaa$morph,data_hpmaa$dmaa)
```

##Test with mixed effect model
```{r}
model_hp <- lmer(dhp ~ treatment*morph + (1|colony) + (1|tank) ,
                   data=data_hpmaa, REML=FALSE)
summary(model_hp)
anova(model_hp)

model_hp1 <- lmer(dhp ~ treatment + (1|colony) + (1|tank) ,
                   data=data_hpmaa, REML=FALSE) 

model_hp2 <- lmer(dhp ~ morph + (1|colony) + (1|tank) ,
                   data=data_hpmaa, REML=FALSE)

anova(model_hp, model_hp1)
anova(model_hp, model_hp2)

model_maa <- lmer(dmaa ~ treatment*morph + (1|colony) + (1|tank) ,
                   data=data_hpmaa, REML=FALSE)
summary(model_maa)
anova(model_maa)

model_maa1 <- lmer(dmaa ~ treatment + (1|colony) + (1|tank) ,
                   data=data_hpmaa, REML=FALSE)

model_maa2 <- lmer(dmaa ~ morph + (1|colony) + (1|tank) ,
                   data=data_hpmaa, REML=FALSE)

anova(model_maa, model_maa1)
anova(model_maa, model_maa2)

```
##Check the LMM assumptions
#Check the normality of model residuals
```{r}
qqnorm(resid(model_hp))
qqline(resid(model_hp))

qqnorm(resid(model_maa))
qqline(resid(model_maa))
```
#Check for homogenity of variance
```{r}
plot(model_hp)
plot(model_maa)
```
##Obtain mean and SD
```{r}
sumfun <- function(x, ...){
  c(mean=mean(x, na.rm=TRUE, ...), sd=sd(x, na.rm=TRUE, ...), l=length(x))
}

mean(data_hpmaa$hpt0, na.rm = TRUE)
sd(data_hpmaa$hpt0, na.rm = TRUE)
mean(data_hpmaa$hpt1, na.rm = TRUE)
sd(data_hpmaa$hpt1, na.rm = TRUE)

summaryBy(hpt0 ~morph * treatment, data=data_hpmaa, FUN=sumfun)
summaryBy(hpt0 ~morph, data=data_hpmaa, FUN=sumfun)
summaryBy(hpt0 ~treatment, data=data_hpmaa, FUN=sumfun)
summaryBy(hpt1 ~morph * treatment, data=data_hpmaa, FUN=sumfun)
summaryBy(hpt1 ~morph, data=data_hpmaa, FUN=sumfun)
summaryBy(hpt1 ~treatment, data=data_hpmaa, FUN=sumfun)
summaryBy(php ~morph * treatment, data=data_hpmaa, FUN=sumfun)
summaryBy(php ~morph, data=data_hpmaa, FUN=sumfun)
summaryBy(php ~treatment, data=data_hpmaa, FUN=sumfun)

summaryBy(maat0 ~morph * treatment, data=data_hpmaa, FUN=sumfun)
summaryBy(maat0 ~morph, data=data_hpmaa, FUN=sumfun)
summaryBy(maat0 ~treatment, data=data_hpmaa, FUN=sumfun)
summaryBy(maat1 ~morph * treatment, data=data_hpmaa, FUN=sumfun)
summaryBy(maat1 ~morph, data=data_hpmaa, FUN=sumfun)
summaryBy(maat1 ~treatment, data=data_hpmaa, FUN=sumfun)
summaryBy(pmaa ~morph * treatment, data=data_hpmaa, FUN=sumfun)
summaryBy(pmaa ~morph, data=data_hpmaa, FUN=sumfun)
summaryBy(pmaa ~treatment, data=data_hpmaa, FUN=sumfun)
```
##Visualize the data as a box plot
```{r message=FALSE, warning=FALSE}
hp_plot <- ggplot(data = data_hpmaa, aes(x=morph, y=php)) + 
  geom_boxplot(aes(fill=treatment)) +
  labs(title= "Host protein concentration (ugproteinmgtissu) concentration", x="Fluorescence morph", y="Relative change (%)") + 
  geom_hline(yintercept=0, color= "red", size = 1.25, alpha = 0.4) +
  ylim(-100, 150) +
  scale_fill_grey(start = 0.4, end = 0.8, name="Treatment",breaks=c("par", "paruv"), labels=c("PAR","PAR+UV")) + 
  theme_bw() +
  theme(legend.position="none")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

hp_plot

maa_plot <- ggplot(data = data_hpmaa, aes(x=morph, y=pmaa)) + 
  geom_boxplot(aes(fill=treatment)) +
  labs(title = "MAA concentration (abs320 nmmgtissu)", x="Fluorescence morph", y="Relative change (%)") + 
  geom_hline(yintercept=0, color= "red", size = 1.25, alpha = 0.4) +
  ylim(-100, 150) +
  scale_fill_grey(start = 0.4, end = 0.8, name="Treatment",breaks=c("par", "paruv"), labels=c("PAR","PAR+UV")) + 
  theme_bw() +
  theme(legend.position="right")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 

  
maa_plot

```